pipelines:
  default:
        - step:
            name: Build Docker Image
            image: atlassian/pipelines-awscli
            runs-on: 
              - 'self.hosted'  
            script:
              - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $DOCKER_ECR_REPO_URL
              - docker build -t $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} .
              - docker tag $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
              - docker push $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
        - step:
            name: Deploy to Kubernetes
            deployment: test
            image: bearengineer/awscli-kubectl
            script:
              - aws eks --region eu-central-1 update-kubeconfig --name prod-cluster
              - kubectl set image deployment/$K8s_DEPLOYMENT_NAME $K8s_DEPLOYMENT_NAME=$DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} --namespace=K8s_NAMESPACE  --local=false
options:
  docker: true
  
  
  
  