pipelines:
  default:
        - step:
            name: Build Docker Image
            image: atlassian/pipelines-awscli
            runs-on: 
              - 'self.hosted'  
            script:
              - echo $(aws ecr get-login --no-include-email --region us-west-2)  > login.sh
              - sh login.sh
              - docker build -t $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} .
              - docker tag $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
              - docker push $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
        - step:
            name: Deploy to Production
            deployment: Production
            script:
              - echo DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
options:
  docker: true