pipelines:
  default:
        - step:
            name: Build Docker Image
            image: atlassian/pipelines-awscli
            runs-on: 
              - 'self.hosted'  
            script:
              - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $DOCKER_ECR_REPO_URL
              - docker build -t $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} .
              - docker tag $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
              - docker push $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}
        - step:
            name: Deploy to Kubernetes
            deployment: test
            image: atlassian/pipelines-kubectl
            script:
              - kubectl config set-cluster kubernetes --certificate-authority=ca.crt --server=$K8s_SERVER_URL
              - kubectl config set-credentials $K8s_USERNAME --token=$K8s_USER_TOKEN
              - kubectl config set-context aws --cluster=kubernetes --namespace=$K8s_NAMESPACE --user=$K8s_USERNAME
              - kubectl config use-context aws --user=$K8s_USERNAME
              - kubectl set image deployment/$K8s_DEPLOYMENT_NAME $K8s_DEPLOYMENT_NAME=$DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} --user=$K8s_USERNAME --local=false
options:
  docker: true
  
  