version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - project
    ports:
      - 5021:3000
    env_file:
      .env

  db:
    image: postgres:14.3-alpine
    volumes:
      - db-data:${DB_DATA_PATH}
    networks:
      - project
    ports:
      - ${DB_OUT_PORT}:${DB_INTER_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_DATA_PATH}

volumes:
  db-data:

networks:
  project:
    driver: bridge
